all: 
	echo "clean, run_server, run_client, build_server, build_client"
build_server:
	gcc tcp_server.c -o a.server
run_server:
	./a.server
build_client:
	gcc tcp_client.c -o a.client
run_client:
	./a.client
clean:
	rm a.client a.server


